### PR TITLE
FFLAGS, CFLAGS, LDFLAGS, and FLIBS are respected by makenek

### PR DESCRIPTION
**Pull request by RonRahaman**
These fixes will allow makenek to respect variables used by GNU make and autoools.  These include:
- FFLAGS
- CFLAGS
- LDFLAGS
- FLIBS

The ordering of the variables in makefile.template may need some improvement.  Thoughts?

### CODE REVIEW

**Comment by RonRahaman** [comment]
For example, I wasn't sure if `$(USR_LFLAGS)` should be appended or prepended to `"$(FLIBS) $(LDFLAGS)"`

**Comment by vijaysm** [comment]
`FLIBS` should be appended to `LIBS`. And `USR_LFLAGS` should be appended to `LDFLAGS`.

**Comment by RonRahaman** [comment]
In that case, should the link line in makenek.template use  `LIBS` and `LDFLAGS` instead of  `lFLAGS``?

**Comment by vijaysm** [comment]
Yes `LIBS` and `LDFLAGS` are standard. But as long as you correctly propagate the flags to the compiler and linker, I don't see any problem with using intermediate variables.

**Pull request merged**
